# Generated by Django 5.2.1 on 2025-06-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padaria',
            name='login_padaria',
        ),
        migrations.RemoveField(
            model_name='padaria',
            name='senha_padaria',
        ),
        migrations.CreateModel(
            name='Padaria_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_padaria', models.TextField()),
                ('senha_padaria', models.TextField()),
                ('padaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.padaria')),
            ],
        ),
    ]
