# Generated by Django 5.2.1 on 2025-06-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_usuario_pessoa_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_previsto', models.DateTimeField()),
                ('padaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.padaria')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('fornada_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.fornada')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.pessoa_usuario')),
            ],
        ),
    ]
