# Generated by Django 5.2.1 on 2025-06-01 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_fornada_notificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornada',
            old_name='padaria_id',
            new_name='padaria',
        ),
        migrations.RenameField(
            model_name='fornada',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='inscricao_usuario_padaria',
            old_name='padaria_id',
            new_name='padaria_usuario',
        ),
        migrations.RenameField(
            model_name='inscricao_usuario_padaria',
            old_name='usuario_id',
            new_name='pessoa_usuario',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='fornada_id',
            new_name='fornada',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='usuario_id',
            new_name='pessoa_usuario',
        ),
        migrations.RenameField(
            model_name='padaria_produtos',
            old_name='padaria_id',
            new_name='padaria',
        ),
        migrations.RenameField(
            model_name='padaria_produtos',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='padaria_usuario',
            old_name='padaria_id',
            new_name='padaria',
        ),
        migrations.AlterField(
            model_name='pessoa_usuario',
            name='pessoa_cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.pessoa', verbose_name='pessoa_cpf'),
        ),
    ]
